### ISSUE TITLE
Create/Update Records is not working with Lookup (EntityReference) field

### ISSUE THREAD

**Issue by Hardik486** [microsoft/PowerPlatform-CdsServiceClient#46] opened 2020-08-24 06:07 UTC
I  have created console application in .Net Core 3.1 and used “Microsoft.PowerPlatform.Cds.Client” (version - 0.2.16-Alpha) 
 
I faced the issue while creating and updating the records with Lookup fields. We fetched the Account and Coupon (custom entity) based on field value and then used those values to set lookup field and we got below error. I already verified all entities and fields name in dynamics and everything is correct in this application.

![Bug-2](https://user-images.githubusercontent.com/70128720/91009196-aec73980-e5fd-11ea-8194-2aef27e3aa84.png)
![Bug-1](https://user-images.githubusercontent.com/70128720/91009200-aff86680-e5fd-11ea-9142-b60f8bb11d4a.png)

**Comment by MattB-msft** [comment] 2020-08-24 23:32
This is a duplicate of https://github.com/microsoft/PowerPlatform-CdsServiceClient/issues/44

**Closed** 2020-08-26 20:40 UTC
