### ISSUE TITLE
'Object reference not set to an instance of an object' while performing upsert requests.

### ISSUE THREAD

**Issue by mathiasbl** [microsoft/PowerPlatform-CdsServiceClient#53] opened 2020-09-14 09:21 UTC
I'm getting 'Object reference not set to an instance of an object' while using upserts.

This is example code.
```
  var entity = new Microsoft.Xrm.Sdk.Entity("account", "rkv_ctscode", "11111");
  entity["name"] = "test";

  client.Execute(new UpsertRequest { Target = entity });
```

Stack:
   at Microsoft.PowerPlatform.Cds.Client.CdsServiceClient.Execute(OrganizationRequest request)
   at ConsoleApp2.Program.Main(String[] args) in C:\xxxs\ConsoleApp2\Program.cs:line 19

When viewing the request in fiddler everything looks OK.

![image](https://user-images.githubusercontent.com/16224711/93068125-5cb58900-f67c-11ea-916c-1ca7bc989e21.png)

**Comment by mathiasbl** [comment] 2020-09-14 09:28
Looks like UpsertRequest is not handled when trying to parse the result.
https://github.com/microsoft/PowerPlatform-CdsServiceClient/blob/bd5dee5c8ecef545b2cede3fcaedc0fff0fa7abf/src/GeneralTools/CDSClient/Client/CdsServiceClient.cs#L5068

**Comment by MattB-msft** [comment] 2020-09-14 21:01
Duplicate of https://github.com/microsoft/PowerPlatform-CdsServiceClient/issues/50

**Closed** 2020-09-15 19:32 UTC
Labels: duplicate

**Comment by mathiasbl** [comment] 2020-09-15 19:53
@MattB-msft this is actually a different issue then the one you linked.

**Comment by mathiasbl** [comment] 2020-09-15 20:18
When using upsert in combination with alternate key you get a null reference from the client. Tested with latest version. 0.2.23-alpha

![image](https://user-images.githubusercontent.com/16224711/93260179-4d7c2b80-f7a1-11ea-9f16-3240056dd5b5.png)
