### ISSUE TITLE
An undeclared property 'customer_entity' which only has property annotations in the payload but no property value was found in the payload

### ISSUE THREAD

**Issue by UM001** [microsoft/PowerPlatform-CdsServiceClient#31] opened 2020-07-19 21:24 UTC
Problem:
An error occurred while validating input parameters: Microsoft.OData.ODataException: An undeclared property 'customer_entity' which only has property annotations in the payload but no property value was found in the payload. In OData, only declared navigation properties and declared named streams can be represented as properties without values.

Cause:
The cdsclient makes lower cases, and sends that to CDS instead of obeying the schema name. of all related custom data types with has upper case. So prefix_MyCustomType becomes prefix_mycustomtype and throws this error.
entity["prefix_MyCustomType@odata.bind"] = "/prefix_mycustomtypes(6b04618d-5e48-e811-811f-5065f38ada

If the entity is sent with CRM REST builder with caps there is not a problem at all.
Requested fix:
1. do use different JSON library which does not make lower case;
2. make the CDS lower/upper case unaware so that it is also easier to code;
3. patch is to rename all custom entities to lower case so the cds client will work. How to do this?

**Comment by MattB-msft** [comment] 2020-07-20 03:00
Interesting find. 
Are you reporting an issue with the way CdsServcieClient is doing the translation of a lookups or are you reporting a general OData behavior with the CDS WebAPI?

I ask because the CdsService is not actually casting entity type names, its picking them up from CDS metadata, for this very reason.  We will take a look here and see if there is a problem with that code,  as it should be following whatever the server requires for that entity name when it casts up or down. 

if your reporting it with CdsServiceClient can you provide an example solution and use case with the client so we can make sure we add a repro of that type to our test matrix? 

thanks
MattB.

**Comment by UM001** [comment] 2020-07-20 16:27
I reproduces this issues on related tables with a custom solution.

`   [TestMethod]
        public void TestCamelCase()
        {
  
            Entity myEntity = new Entity("v4a_mytable");
   
            myEntity.Attributes.Add("v4a_mylowercasefield", "Lower3");
            myEntity.Attributes.Add("v4a_mycamelcasefield", "Camel4");
            myEntity.Attributes.Add("v4a_myrelatedcamelcasefield@odata.bind", $"/v4a_mylookupcamelcasetables(65444359-9fca-ea11-a812-000d3abac826)");
            myEntity.Attributes.Add("v4a_mylookuplowercasetable@odata.bind", $"/v4a_mylookuplowercasetables(070b7229-9fca-ea11-a812-000d3abac826)");

            myEntity.Attributes.Add("statecode", ((int) 1).ToString());

            var result = _cdsServiceClient.Create(myEntity);

        }`
It throws this error which is in from the response and request of the view exceptions so I assume this is sent. I cannot install fiddler to see what is actually send to the CRM api.

`{"error":{"code":"0x0","message":"An error occurred while validating input parameters: Microsoft.OData.ODataException: An undeclared property 'v4a_myrelatedcamelcasefield' which only has property annotations in the payload but no property value was found in the payload. In OData, only declared navigation properties and declared named streams can be represented as properties without values.\r\n   at `

What is submitted here is:
`{"v4a_mylowercasefield":"Lower3","v4a_mycamelcasefield":"Camel4","v4a_myrelatedcamelcasefield@odata.bind":"/v4a_mylookupcamelcasetables(65444359-9fca-ea11-a812-000d3abac826)","v4a_mylookuplowercasetable@odata.bind":"/v4a_mylookuplowercasetables(070b7229-9fca-ea11-a812-000d3abac826)","statecode":"1"}`

Now doing the same with CRM REST builder with lower case --> no record created.
`
var entity = {};
entity["v4a_myrelatedcamelcasefield@odata.bind"] = "/v4a_mylookupcamelcasetables(65444359-9fca-ea11-a812-000d3abac826)";
entity["v4a_mylookuplowercasetable@odata.bind"] = "/v4a_mylookuplowercasetables(070b7229-9fca-ea11-a812-000d3abac826)";
entity.v4a_mylowercasefield = "test";
entity.v4a_mycamelcasefield = "CamelCase";

var req = new XMLHttpRequest();
req.open("POST", Xrm.Page.context.getClientUrl() + "/api/data/v9.1/v4a_mytables", true);
req.setRequestHeader("OData-MaxVersion", "4.0");
req.setRequestHeader("OData-Version", "4.0");
req.setRequestHeader("Accept", "application/json");
req.setRequestHeader("Content-Type", "application/json; charset=utf-8");
req.onreadystatechange = function() {
    if (this.readyState === 4) {
        req.onreadystatechange = null;
        if (this.status === 204) {
            var uri = this.getResponseHeader("OData-EntityId");
            var regExp = /\(([^)]+)\)/;
            var matches = regExp.exec(uri);
            var newEntityId = matches[1];
        } else {
            Xrm.Utility.alertDialog(this.statusText);
        }
    }
};
req.send(JSON.stringify(entity));
`
Now with camelcase for the camelcase related fields. The regular camelcase and lowercase field are inserted without making difference of camel or lower.
`
var entity = {};
entity["v4a_MyRelatedCamelCaseField@odata.bind"] = "/v4a_mylookupcamelcasetables(65444359-9fca-ea11-a812-000d3abac826)";
entity["v4a_mylookuplowercasetable@odata.bind"] = "/v4a_mylookuplowercasetables(070b7229-9fca-ea11-a812-000d3abac826)";
entity.v4a_mylowercasefield = "test";
entity.v4a_mycamelcasefield = "CamelCase";

var req = new XMLHttpRequest();
req.open("POST", Xrm.Page.context.getClientUrl() + "/api/data/v9.1/v4a_mytables", true);
req.setRequestHeader("OData-MaxVersion", "4.0");
req.setRequestHeader("OData-Version", "4.0");
req.setRequestHeader("Accept", "application/json");
req.setRequestHeader("Content-Type", "application/json; charset=utf-8");
req.onreadystatechange = function() {
    if (this.readyState === 4) {
        req.onreadystatechange = null;
        if (this.status === 204) {
            var uri = this.getResponseHeader("OData-EntityId");
            var regExp = /\(([^)]+)\)/;
            var matches = regExp.exec(uri);
            var newEntityId = matches[1];
        } else {
            Xrm.Utility.alertDialog(this.statusText);
        }
    }
};
req.send(JSON.stringify(entity));
`

**Comment by UM001** [comment] 2020-07-20 20:50
I suspect here the tolower() is. I did not run the code. I tried first to use an entity reference, but that did not work either. I guess it is in this code. Meanwhile I am reworking an example of 'CDSWebApiService'. I rewrite it as with dependency injection the httpclient can get exhausted. For that reason I am adding a MSAL handler of another example to see if that works. Bit more coding tough, but I need it.

`/// <summary>
		/// Parses an attribute array into a object that can be used to create a JSON request. 
		/// </summary>
		/// <param name="entityAttributes"></param>
		/// <param name="mUtil"></param>
		/// <returns></returns>
		internal static ExpandoObject ToExpandoObject(AttributeCollection entityAttributes , MetadataUtility mUtil)
		{
			dynamic expando = new ExpandoObject();
			var expandoObject = ((IDictionary<string, object>)(expando));
			var attributes = entityAttributes.ToArray();
			foreach (var attrib in entityAttributes)
			{
				var keyValuePair = attrib;
				var value = keyValuePair.Value;
				var key = keyValuePair.Key;
				if (value is EntityReference entityReference)
				{
					key = $"{key}@odata.bind";
					value = $"/{mUtil.GetEntityMetadata(Xrm.Sdk.Metadata.EntityFilters.Entity, entityReference.LogicalName).EntitySetName}({entityReference.Id})";
				}
				else
				{
					key = key.ToLower();
					if (value is OptionSetValueCollection optionSetValues)
					{
						string mselectValueString = string.Empty;
						foreach (var opt in optionSetValues)
						{
							mselectValueString += $"{opt.Value.ToString()},";
						}
						value = mselectValueString.Remove(mselectValueString.Length -1 );
					}
					else if (value is OptionSetValue optionSetValue)
					{
						value = optionSetValue.Value.ToString();
					}
					else if (value is DateTime dateTimeValue)
					{
						value = dateTimeValue.ToUniversalTime().ToString("yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fff'Z'");
					}
					else if (value is Money moneyValue)
					{
						value = moneyValue.Value;
					}
					else if (value is bool boolValue)
					{
						value = boolValue.ToString();
					}
					else if (value is Guid guidValue)
					{
						value = guidValue.ToString();
					}
					else if (value is null)
					{
						value = "";
					}
				}
				expandoObject.Add(key, value);
			}
			return ((ExpandoObject)(expandoObject));
		}`

**Comment by UM001** [comment] 2020-07-20 23:22
I programmed my version of CDSWebApiService with MSAL. I confirm that sending a request to the CDS with lower cases and not taking care of the schema name throws error. So this library should not lower case anything till somebody at the CDS site fixes this. It is a bit ackward that the datamodel is that strict as you cannot define 2 similar field names: one in lower and one in uppercase.

What is the expectation to have this investigated and fixed? Then I can decide to step deeper into this library.

` var mytableEntry = new JObject
            {
                { "v4a_mylowercasefield", "Lower3" },
                { "v4a_mycamelcasefield", "Camel4" },
                //{ "v4a_myrelatedcamelcasefield@odata.bind", $"/v4a_mylookupcamelcasetables(65444359-9fca-ea11-a812-000d3abac826)" },
                //^throws error
                { "v4a_MyRelatedCamelCaseField@odata.bind", $"/v4a_mylookupcamelcasetables(65444359-9fca-ea11-a812-000d3abac826)" },
                { "v4a_mylookuplowercasetable@odata.bind", $"/v4a_mylookuplowercasetables(070b7229-9fca-ea11-a812-000d3abac826)" }
            };
            
            var myNewTableEntryUri = _d365CeService.PostCreate("v4a_mytables", mytableEntry);`

**Comment by MattB-msft** [comment] 2020-07-21 05:09
This example: 

>  Entity myEntity = new Entity("v4a_mytable");
        myEntity.Attributes.Add("v4a_mylowercasefield", "Lower3");
        myEntity.Attributes.Add("v4a_mycamelcasefield", "Camel4");
        myEntity.Attributes.Add("v4a_myrelatedcamelcasefield@odata.bind", $"/v4a_mylookupcamelcasetables(65444359-9fca-ea11-a812-000d3abac826)");
        myEntity.Attributes.Add("v4a_mylookuplowercasetable@odata.bind", $"/v4a_mylookuplowercasetables(070b7229-9fca-ea11-a812-000d3abac826)");

        myEntity.Attributes.Add("statecode", ((int) 1).ToString());

        var result = _cdsServiceClient.Create(myEntity);

is incorrect. 

Where you to use that in CdsServiceClient you would do that using EntityReferance(https://docs.microsoft.com/en-us/dotnet/api/microsoft.xrm.sdk.entityreference?view=dynamics-general-ce-9).
in the case above,,         
myEntity.Attributes.Add("v4a_mylookuplowercasetable@odata.bind", $"/v4a_mylookuplowercasetables(070b7229-9fca-ea11-a812-000d3abac826)")
Should be 
myEntity.Attributes.Add("v4a_mylookuplowercasetableid", new EntityReferance("v4a_mylookuplowercasetables", Guid.Parse(070b7229-9fca-ea11-a812-000d3abac826))); 


The CdsServiceClient Exposes the OrganizationAPI for CDS.  Documented here: 
https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/overview
if you want to use the lowerlevel Odata API, "the Web API" you can use the CdsServiceClient to do it using the _cdsServiceClient.ExecuteCdsWebRequest method. 

We will take a look at your examples see if the problem surfaces in the CdsServiceClient.   
Insofar as the general webAPI for CDS, it is case sensitive by design.

**Comment by UM001** [comment] 2020-07-21 11:13
Thank you. I started looking into these alternatives a a strong-typed custom entity did not work this way.
Your code works with a small fixes for the typo's: no plural s for entity reference, and no id for the foreign key fields.
I went this way because the strongtyped entities do make them lower case. I created that test case as well. See below first the working case with setting the attributes manually in caps. 

`           Entity myEntity = new Entity("v4a_mytable");

            myEntity.Attributes.Add("v4a_mylowercasefield", "Lower3");
            myEntity.Attributes.Add("v4a_mycamelcasefield", "Camel4");
            //myEntity.Attributes.Add("v4a_MyRelatedCamelCaseField@odata.bind", $"/v4a_mylookupcamelcasetables(65444359-9fca-ea11-a812-000d3abac826)");
            //myEntity.Attributes.Add("v4a_mylookuplowercasetable@odata.bind", $"/v4a_mylookuplowercasetables(070b7229-9fca-ea11-a812-000d3abac826)");

            myEntity.Attributes.Add("v4a_MyRelatedCamelCaseField", new EntityReference("v4a_mylookupcamelcasetable", Guid.Parse("65444359-9fca-ea11-a812-000d3abac826")));
            myEntity.Attributes.Add("v4a_mylookuplowercasetable", new EntityReference("v4a_mylookuplowercasetable", Guid.Parse("070b7229-9fca-ea11-a812-000d3abac826")));


            myEntity.Attributes.Add("statecode", ((int)1).ToString());

            var result = _cdsServiceClient.Create(myEntity);`

Now the strong typed version generated with crmutil:

'{"v4a_mylowercasefield":"lower3","v4a_mycamelcasefield":"Camel2","v4a_mylookuplowercasetable@odata.bind":"/v4a_mylookuplowercasetables(070b7229-9fca-ea11-a812-000d3abac826)","v4a_myrelatedcamelcasefield@odata.bind":"/v4a_mylookupcamelcasetables(65444359-9fca-ea11-a812-000d3abac826)","statecode":"0"}'

**Comment by MattB-msft** [comment] 2020-08-03 23:02
Ok so we have looked though your report here.. 
the CDS WebAPI is case sensitive, which is by design, and we have confirmed that the CdsServiceClient is doing translations correctly. 

I am going to close this up now as its by design.

**Closed by MattB-msft** 2020-08-03 23:02 UTC
