### ISSUE TITLE
Impersonation does not seem to work on a Cloned client instance

### ISSUE THREAD

**Issue by dsmeltz** [microsoft/PowerPlatform-CdsServiceClient#33] opened 2020-07-24 15:21 UTC
Using the CdsServiceClient does not seem to apply any impersonation while running in a web context. (ASP.Net Core)

I've set both CallerAADObjectId and CallerId on the client and neither one make a difference.  Data requests are issued as the Application User without any impersonation applied.  (The Application User has the Delegate role in Dynamics)

I used the exact same code in a console app and the impersonation works without issue.

My configuration for the CdsServiceClient is the same for both the web application and the console app.  (Actually a LinqPad query)

Update:  After some experimentation, I discovered that if you clone the CdsServiceClient, then the impersonation does not work.  Reproduced it my the console app.

**Comment by MattB-msft** [comment] 2020-07-25 03:44
is this current version from Nuget? 
We had this issue reported before and fixed it a while ago..
Affected code that was fixed is here:  ( this was before we started replicating our repro ) 
https://github.com/microsoft/PowerPlatform-CdsServiceClient/blob/2dba0cf766985cbf72ccfb8381b23f918749cc09/src/GeneralTools/CDSClient/Client/CdsServiceClient.cs#L1188

**Comment by dsmeltz** [comment] 2020-07-25 14:10
Yes, the issue exists in the current Nuget package.

It happens when you Clone the CdsServiceClient.  The cloned client will then only execute requests as the Application User and does not apply any impersonation.  I've tried using both CallerAADObjectId and CallerId, together and separately, to no effect.

**Comment by dsmeltz** [comment] 2020-07-25 20:19
Here's a simple example of the problem.

![CdsClientCloneIssue](https://user-images.githubusercontent.com/1830600/88465613-80393000-ce92-11ea-9654-5471219e8a83.jpg)

**Comment by dsmeltz** [comment] 2020-07-27 11:32
Here's the code from the screen shot, cleaned up:

```c#
var cdsClient = new CdsServiceClient(uri, clientId, clientSecret, true, tokenCachePath);
	
var c1 = cdsClient.Clone();
c1.CallerAADObjectId = limitedUserGuid;
c1.CallerId = limitedUserGuid;
var x = GetUserList(c1);
$"Limited User, Clone: {x.Count()}".Dump();
	
var c2 = cdsClient.Clone();
var y = GetUserList(c2);
$"Application User, Clone {y.Count()}".Dump();
	
cdsClient.CallerAADObjectId = limitedUserGuid;
var z = GetUserList(cdsClient);
$"Limited User, No Clone: {z.Count()}".Dump();

private IEnumerable<string> GetUserList(CdsServiceClient cdsClient)
{
	var list = cdsClient.RetrieveMultiple(new QueryExpression("systemuser")
	{
		ColumnSet = new ColumnSet("fullname")
	}).Entities.Select(u => u.GetAttributeValue<string>("fullname"));

	return list;
}
```

**Comment by BetimBeja** [comment] 2020-07-28 03:38
Hello @dsmeltz ,
I found the problem with your code, you are setting the `c1.CallerId = limitedUserGuid;` to a nonexistent user Guid and this makes the client misbehave.

Also @MattB-msft when you try to create a record with the misconfigured caller id the library throws with a strange error and this is the trace I have:
```
Microsoft.Rest.HttpOperationException
  HResult=0x80131500
  Message=Operation returned an invalid status code 'InternalServerError'
  Source=Microsoft.PowerPlatform.Cds.Client
  StackTrace:
   at Microsoft.PowerPlatform.Cds.Client.CdsConnectionService.<ExecuteHttpRequestAsync>d__169.MoveNext()
```

```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred. (Bad JSON escape sequence: \x. Path '_error', line 1, position 170.)
  Source=System.Private.CoreLib
  StackTrace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

Inner Exception 1:
JsonReaderException: Bad JSON escape sequence: \x. Path '_error', line 1, position 170.
```

**Comment by dsmeltz** [comment] 2020-07-28 10:56
I didn't include the GUID for privacy reasons.  (I know it's just a GUID, but you never know.)

You can see by the results that when the limited user GUID is used on a cloned client, it is ignored.  Using the same GUID on the originally instantiated client, returns the correct result of 2.

**Comment by BetimBeja** [comment] 2020-07-28 10:59
> I found the problem with your code, you are setting the c1.CallerId = limitedUserGuid; to a nonexistent user Guid and this makes the client misbehave.

You are setting the `CallerId` with the same value of `CallerAADObjectId` meaning that you are setting it to a non existent Guid (as doesn't match a valid systemuser reference on your Environment)

**Comment by BetimBeja** [comment] 2020-07-28 12:07
@dsmeltz also in [this](https://github.com/microsoft/PowerPlatform-CdsServiceClient/blob/2dba0cf766985cbf72ccfb8381b23f918749cc09/src/GeneralTools/CDSClient/Client/CdsServiceClient.cs#L5546-L5562) piece of code you can understand that `CallerId` has priority over `CallerAADObjectId` and this combined with the fact that the specified `CallerId` does not exist since it is a `CallerAADObjectId`, explains the behavior you are experiencing.

**Comment by dsmeltz** [comment] 2020-07-28 12:19
I tried all the combinations of those two Caller* properties, all ending with the same result.  I just ran my test again, only setting CallerAADObjectId, and received the same result as in the above screen shot.  Using a cloned client, CallerAADObjectId is ignored and the result is 324.  When I set CallerAADObjectId on the main instance of the client, the result is 2, which is expected.

**Comment by dsmeltz** [comment] 2020-07-29 17:09
@MattB-msft I just verified that the line you called out earlier, is indeed in the package I'm using.  I'm not sure where that leaves things as it's very simple for me to reproduce the issue.

**Comment by MattB-msft** [comment] 2020-07-29 21:37
@dsmeltz 
You should never do this: 
c1.CallerAADObjectId = limitedUserGuid;
c1.CallerId = limitedUserGuid;
If your going to use impersonation, you should use one or the other. 

As indicated by @BetimBeja ,  the system prioritizes callerID over CallerAADObjectId. 

CallerID is a Cds User ID (internal key to CDS for any given user),  not an AADObject ID.  thus its going to use CallerID first. 

In your code, can you remove the use of CallerId and see if that resolves it for you?

thanks
MattB

**Comment by dsmeltz** [comment] 2020-07-29 22:53
@MattB-msft  Yes, the last test I ran was after removing all uses of CallerId.  The results were the same.  
Cloned client, limited user, 342 (incorrect count, same result if you don't set the CallerAADObjectId at all)
Uncloned client, limited user, 2 (correct count)

**Comment by MattB-msft** [comment] 2020-08-03 18:18
@dsmeltz  We verified that this is working as intended. 

I see your querying systemuser,  Out of curiosity, did you alter permissions for your users?  by default all users have "read all" priv's for system users via the CDS User security role.   Which means that your query, which does not account for owner, will use the security privilege's assigned, which by default would be "read all" for system users. 

Thus your going to see all of them. regardless of user being used or the owner as the current user has permissions to see all system users.. 

if you want to force filter to _current user's_ data,  Modify your function as follows:

        private static IEnumerable<string> GetUserList(CrmServiceClient cdsClient)
        {
            **var filter = new FilterExpression();
            filter.AddCondition(new ConditionExpression("ownerid", ConditionOperator.EqualUserOrUserTeams));**
            var list = cdsClient.RetrieveMultiple(new QueryExpression("systemuser")
            {
                ColumnSet = new ColumnSet(true),
                **Criteria = filter**
            }).Entities.Select(u => u.GetAttributeValue<string>("fullname"));

            return list;
        }

That will enforce current user ownership of a given record in the return set.
so even though User A can See all system users by security permission,  this will filter the results to only the records that the user directly owns. 

let me if that sorts it out for you

**Comment by dsmeltz** [comment] 2020-08-03 19:55
We have multiple Business Units, by which users are 'fenced in'.  So, the Limited User I'm using, in my code above, should only return a few users.  (All the users of the Business Unit of which Limited User is a member.)  As you can see, in the above output, that does not happen when you use a cloned instance.  It only works when you use the original instantiated instance.

I'm at a loss as to why there would be a difference between the two invocations.  (Cloned and Original Instantiation)

**Comment by MattB-msft** [comment] 2020-08-03 21:01
@dsmeltz  I would ask that you ping support to have a look. 
from what your describing I'm fairly confident that its related to your security role assignments and effective privilege's but I would need to see your environment to confirm that. 

SystemUsers fall under the "Common Data Service Users" which grant read to all organization users. 
take a look at this link: 
https://docs.microsoft.com/en-us/power-platform/admin/wp-security-cds

The graphic in this view: https://docs.microsoft.com/en-us/power-platform/admin/wp-security-cds#entityrecord-ownership outlines what I am talking about. 
Notice that contact has a full green globe for read.  When assigned to a user, that allows that user to see any contact in any business unit.  Thus, if both of your users are configured with a role that grants read organization to system user, like Common Data Service Users,  you will see all records from both users..  

IF your limited user is configured with a security role that grants read to only your business unit ( yellow half circle from the image) , then you should see what your expecting

**Comment by dsmeltz** [comment] 2020-08-04 10:45
That's great information, thanks.  It's how we have things setup in our tenant.  But it still doesn't explain how the CdsServiceClient behaves when it's cloned.  Maybe I'm missing something, but when using an uncloned instance it behaves as expected.  It's only when using a cloned instance that it does not apply the impersonation.  I changed my example code to pull information from one of our custom entities and it had the exact, same behavior.  The cloned client didn't apply impersonation, uncloned worked as expected. 

All this tells me that our security roles are fine.  (If they weren't our users would be in a uproar.)  So the problem must lie elsewhere.

**Comment by MattB-msft** [comment] 2020-08-04 17:30
One thing I want to be clear here with regard to impersonation; 
The actual set of privileges that is used to modify or retrieve data is the **intersection** of the privileges that the impersonator user possesses with that of the impersonated user.

You can read more about it here. https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/impersonate-another-user 

If that does not resolve it for you,  We will need to take a look at what is going on here to see if this is a problem with the service or something about your instance configuration.  To do that we will need you to open a support ticket with this problem and have one of our support folks look at your environment.

**Comment by dsmeltz** [comment] 2020-08-04 17:35
That is exactly what is happening when the impersonation works.  The data is fenced, per the impersonated user.

**Comment by MattB-msft** [comment] 2020-08-04 17:54
Ok,  then Please open the support ticket so we can look into what is going on there.

**Closed by MattB-msft** 2020-08-04 17:54 UTC
